<RockSimDocument>
    <FileVersion>4</FileVersion>
    <DesignInformation>
        <RocketDesign>
            <Name>Estes Saturn V 1/100 scale 30th Anniversary </Name>
            <StageCount>1</StageCount>
            <DisplayFlags>7</DisplayFlags>
            <ViewType>0</ViewType>
            <ViewStageCount>3</ViewStageCount>
            <ViewTypeEdit>0</ViewTypeEdit>
            <ViewStageCountEdit>3</ViewStageCountEdit>
            <ZoomFactor>0.0</ZoomFactor>
            <ZoomFactorEdit>0.0</ZoomFactorEdit>
            <ScrollPosX>0</ScrollPosX>
            <ScrollPosY>0</ScrollPosY>
            <ScrollPosXEdit>0</ScrollPosXEdit>
            <ScrollPosYEdit>0</ScrollPosYEdit>
            <ThreeDFlags>0</ThreeDFlags>
            <ThreeDFlagsEdit>0</ThreeDFlagsEdit>
            <LastSerialNumber>24</LastSerialNumber>
            <Stage3Mass>0.0</Stage3Mass>
            <Stage2Mass>0.0</Stage2Mass>
            <Stage1Mass>0.0</Stage1Mass>
            <Stage3CG>490.8234232529873</Stage3CG>
            <Stage2CGAlone>0.0</Stage2CGAlone>
            <Stage1CGAlone>0.0</Stage1CGAlone>
            <Stage321CG>0.0</Stage321CG>
            <Stage32CG>0.0</Stage32CG>
            <CPCalcFlags>1</CPCalcFlags>
            <CPSimFlags>1</CPSimFlags>
            <UseKnownMass>0</UseKnownMass>
            <Stage3Parts>
                <NoseCone>
                    <KnownMass>5.83147111052119</KnownMass>
                    <Density>1049.2093265</Density>
                    <Material>Polystyrene PS</Material>
                    <Name>Command Module</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>5.83147111052119</CalcMass>
                    <CalcCG>26.295201725104988</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>38.1</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>1</SerialNo>
                    <ShapeCode>0</ShapeCode>
                    <ConstructionType>1</ConstructionType>
                    <WallThickness>2.54</WallThickness>
                    <ShapeParameter>0.0</ShapeParameter>
                    <AttachedParts/>
                    <BaseDia>38.1</BaseDia>
                    <ShoulderLen>0.0</ShoulderLen>
                    <ShoulderOD>0.0</ShoulderOD>
                </NoseCone>
                <BodyTube>
                    <KnownMass>8.047336280341199</KnownMass>
                    <Density>1121.29241</Density>
                    <Material>Paper</Material>
                    <Name>Service Module</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>8.047336280341199</CalcMass>
                    <CalcCG>23.8125</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>47.625</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>2</SerialNo>
                    <OD>39.0398</OD>
                    <ID>36.4998</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>36.4998</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts/>
                </BodyTube>
                <Transition>
                    <KnownMass>19.732947167328106</KnownMass>
                    <Density>1121.29241</Density>
                    <Material>Paper</Material>
                    <Name>LEM Shroud</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>19.732947167328106</CalcMass>
                    <CalcCG>46.79246564300963</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>85.725</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>3</SerialNo>
                    <ShapeCode>0</ShapeCode>
                    <ConstructionType>1</ConstructionType>
                    <WallThickness>1.27</WallThickness>
                    <ShapeParameter>0.0</ShapeParameter>
                    <AttachedParts>
                        <BodyTube>
                            <KnownMass>17.704139816750626</KnownMass>
                            <Density>1121.29241</Density>
                            <Material>Paper</Material>
                            <Name>Body tube</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>0.0</Xb>
                            <CalcMass>17.704139816750626</CalcMass>
                            <CalcCG>52.3875</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>104.775</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>4</SerialNo>
                            <OD>39.0398</OD>
                            <ID>36.4998</ID>
                            <IsMotorMount>0</IsMotorMount>
                            <MotorDia>36.4998</MotorDia>
                            <EngineOverhang>0.0</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts/>
                        </BodyTube>
                    </AttachedParts>
                    <FrontShoulderLen>0.0</FrontShoulderLen>
                    <RearShoulderLen>0.0</RearShoulderLen>
                    <FrontShoulderDia>0.0</FrontShoulderDia>
                    <RearShoulderDia>0.0</RearShoulderDia>
                    <FrontDia>38.1</FrontDia>
                    <RearDia>66.04</RearDia>
                </Transition>
                <BodyTube>
                    <KnownMass>4.267610124146819</KnownMass>
                    <Density>1121.29241</Density>
                    <Material>Paper</Material>
                    <Name>3rd Stage</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>4.267610124146819</CalcMass>
                    <CalcCG>60.325</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>120.65</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>5</SerialNo>
                    <OD>66.04</OD>
                    <ID>65.7352</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>65.7352</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <Ring>
                            <KnownMass>6.459992434302585</KnownMass>
                            <Density>1121.29241</Density>
                            <Material>Paper</Material>
                            <Name>Tube coupler</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>0.0</Xb>
                            <CalcMass>6.459992434302585</CalcMass>
                            <CalcCG>9.525</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>19.05</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>6</SerialNo>
                            <OD>65.7352</OD>
                            <ID>62.738</ID>
                            <UsageCode>4</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>3.1282869783801157</KnownMass>
                            <Density>1121.29241</Density>
                            <Material>Paper</Material>
                            <Name>Ring</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>0.0</Xb>
                            <CalcMass>3.1282869783801157</CalcMass>
                            <CalcCG>0.635</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>1.27</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>7</SerialNo>
                            <OD>65.7352</OD>
                            <ID>39.0398</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>3.1282869783801157</KnownMass>
                            <Density>1121.29241</Density>
                            <Material>Paper</Material>
                            <Name>Ring</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>19.05</Xb>
                            <CalcMass>3.1282869783801157</CalcMass>
                            <CalcCG>0.635</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>1.27</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>8</SerialNo>
                            <OD>65.7352</OD>
                            <ID>39.0398</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>0.9014501011507209</KnownMass>
                            <Density>160.18463</Density>
                            <Material>Vac-Form Plastic</Material>
                            <Name>Lower 3rd Stage Wrapper</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>0.9014501011507209</CalcMass>
                            <CalcCG>10.4775</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>20.955</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>9</SerialNo>
                            <OD>68.58</OD>
                            <ID>66.04</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>1.3658334865920017</KnownMass>
                            <Density>160.18463</Density>
                            <Material>Vac-Form Plastic</Material>
                            <Name>Upper 3rd Stage Wrapper</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>0.0</Xb>
                            <CalcMass>1.3658334865920017</CalcMass>
                            <CalcCG>15.875</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>31.75</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>10</SerialNo>
                            <OD>68.58</OD>
                            <ID>66.04</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                    </AttachedParts>
                </BodyTube>
                <Transition>
                    <KnownMass>43.51657716047498</KnownMass>
                    <Density>1049.2093265</Density>
                    <Material>Polystyrene PS</Material>
                    <Name>3rd Stage Reduction</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>43.51657716047498</CalcMass>
                    <CalcCG>32.222328957160954</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>60.325</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>11</SerialNo>
                    <ShapeCode>0</ShapeCode>
                    <ConstructionType>1</ConstructionType>
                    <WallThickness>2.54</WallThickness>
                    <ShapeParameter>0.0</ShapeParameter>
                    <AttachedParts>
                        <BodyTube>
                            <KnownMass>3.369165887484269</KnownMass>
                            <Density>1121.29241</Density>
                            <Material>Paper</Material>
                            <Name>Internal 3rd Stage tube</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>0.0</Xb>
                            <CalcMass>3.369165887484269</CalcMass>
                            <CalcCG>47.625</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>95.25</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>12</SerialNo>
                            <OD>66.04</OD>
                            <ID>65.7352</ID>
                            <IsMotorMount>0</IsMotorMount>
                            <MotorDia>65.7352</MotorDia>
                            <EngineOverhang>0.0</EngineOverhang>
                            <IsInsideTube>1</IsInsideTube>
                            <AttachedParts/>
                        </BodyTube>
                    </AttachedParts>
                    <FrontShoulderLen>0.0</FrontShoulderLen>
                    <RearShoulderLen>0.0</RearShoulderLen>
                    <FrontShoulderDia>0.0</FrontShoulderDia>
                    <RearShoulderDia>0.0</RearShoulderDia>
                    <FrontDia>68.58</FrontDia>
                    <RearDia>102.5652</RearDia>
                </Transition>
                <BodyTube>
                    <KnownMass>117.28425797392029</KnownMass>
                    <Density>1121.29241</Density>
                    <Material>Paper</Material>
                    <Name>1st / 2nd Stage</Name>
                    <KnownCG>0.0</KnownCG>
                    <UseKnownCG>0</UseKnownCG>
                    <Xb>0.0</Xb>
                    <CalcMass>117.28425797392029</CalcMass>
                    <CalcCG>313.69</CalcCG>
                    <DensityType>0</DensityType>
                    <RadialLoc>0.0</RadialLoc>
                    <RadialAngle>0.0</RadialAngle>
                    <LocationMode>0</LocationMode>
                    <Len>627.38</Len>
                    <FinishCode>2</FinishCode>
                    <SerialNo>13</SerialNo>
                    <OD>100.0252</OD>
                    <ID>98.9584</ID>
                    <IsMotorMount>0</IsMotorMount>
                    <MotorDia>98.9584</MotorDia>
                    <EngineOverhang>0.0</EngineOverhang>
                    <IsInsideTube>0</IsInsideTube>
                    <AttachedParts>
                        <FinSet>
                            <KnownMass>3.41504647485158</KnownMass>
                            <Density>80.092315</Density>
                            <Material>Vac-Form Plastic</Material>
                            <Name>Fin set</Name>
                            <KnownCG>32.5458666666667</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>6.35</Xb>
                            <CalcMass>2.902789503623837</CalcMass>
                            <CalcCG>32.5458666666667</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>2</FinishCode>
                            <SerialNo>14</SerialNo>
                            <FinCount>4</FinCount>
                            <RootChord>50.8</RootChord>
                            <TipChord>17.4752</TipChord>
                            <SemiSpan>55.88</SemiSpan>
                            <SweepDistance>33.7312</SweepDistance>
                            <Thickness>5.588</Thickness>
                            <ShapeCode>0</ShapeCode>
                            <TipShapeCode>2</TipShapeCode>
                            <TabLength>0.0</TabLength>
                            <TabDepth>0.0</TabDepth>
                            <TabOffset>0.0</TabOffset>
                            <SweepMode>1</SweepMode>
                            <CantAngle>0.0</CantAngle>
                        </FinSet>
                        <Ring>
                            <KnownMass>4.933081308252602</KnownMass>
                            <Density>160.18463</Density>
                            <Material>Vac-Form Plastic</Material>
                            <Name>Lower 1st Stage Wrapper</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>-0.0</Xb>
                            <CalcMass>4.933081308252602</CalcMass>
                            <CalcCG>38.1</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>76.2</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>15</SerialNo>
                            <OD>102.5652</OD>
                            <ID>100.0252</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>4.521991199231551</KnownMass>
                            <Density>160.18463</Density>
                            <Material>Vac-Form Plastic</Material>
                            <Name>InterTank Wrapper</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>146.05</Xb>
                            <CalcMass>4.521991199231551</CalcMass>
                            <CalcCG>34.925</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>69.85</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>16</SerialNo>
                            <OD>102.5652</OD>
                            <ID>100.0252</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>7.810712071399954</KnownMass>
                            <Density>160.18463</Density>
                            <Material>Vac-Form Plastic</Material>
                            <Name>Inter Stage Wrapper</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>349.25</Xb>
                            <CalcMass>7.810712071399954</CalcMass>
                            <CalcCG>60.325</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>2</LocationMode>
                            <Len>120.65</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>17</SerialNo>
                            <OD>102.5652</OD>
                            <ID>100.0252</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Ring>
                            <KnownMass>2.2609955996157756</KnownMass>
                            <Density>160.18463</Density>
                            <Material>Vac-Form Plastic</Material>
                            <Name>Upper 2nd Stage Wrapper</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>0.0</Xb>
                            <CalcMass>2.2609955996157756</CalcMass>
                            <CalcCG>17.4625</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>34.925</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>18</SerialNo>
                            <OD>102.5652</OD>
                            <ID>100.0252</ID>
                            <UsageCode>0</UsageCode>
                            <AutoSize>0</AutoSize>
                        </Ring>
                        <Parachute>
                            <KnownMass>5.896700784</KnownMass>
                            <Density>1.1331831948142947E-8</Density>
                            <Material>Polyethylene LDPE</Material>
                            <Name>Main Chutes 1 &amp; 2</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>57.15</Xb>
                            <CalcMass>0.65108587348224</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>1</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>25.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>19</SerialNo>
                            <Dia>609.6</Dia>
                            <ShroudLineCount>6</ShroudLineCount>
                            <Thickness>0.0</Thickness>
                            <ShroudLineLen>609.6</ShroudLineLen>
                            <ChuteCount>1</ChuteCount>
                            <ShroudLineMassPerMM>1.78E-4</ShroudLineMassPerMM>
                            <ShroudLineMaterial>30 Lb. kevlar</ShroudLineMaterial>
                            <DragCoefficient>0.75</DragCoefficient>
                        </Parachute>
                        <Parachute>
                            <KnownMass>5.896700784</KnownMass>
                            <Density>7.554554632095298E-9</Density>
                            <Material>Polyethylene LDPE</Material>
                            <Name>Nose Cone Parachute</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>0.0</Xb>
                            <CalcMass>0.4883020025558399</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>1</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>25.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>20</SerialNo>
                            <Dia>457.2</Dia>
                            <ShroudLineCount>6</ShroudLineCount>
                            <Thickness>0.0</Thickness>
                            <ShroudLineLen>457.2</ShroudLineLen>
                            <ChuteCount>1</ChuteCount>
                            <ShroudLineMassPerMM>1.78E-4</ShroudLineMassPerMM>
                            <ShroudLineMaterial>30 Lb. kevlar</ShroudLineMaterial>
                            <DragCoefficient>0.75</DragCoefficient>
                        </Parachute>
                        <MassObject>
                            <KnownMass>10.42416</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Mass object</Name>
                            <KnownCG>85.725</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>85.725</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>27.432</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>21</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <MassObject>
                            <KnownMass>48.1941891</KnownMass>
                            <Density>0.0</Density>
                            <Material></Material>
                            <Name>Paint Glue, etc.</Name>
                            <KnownCG>311.15</KnownCG>
                            <UseKnownCG>1</UseKnownCG>
                            <Xb>311.15</Xb>
                            <CalcMass>0.0</CalcMass>
                            <CalcCG>0.0</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>0.0</Len>
                            <FinishCode>0</FinishCode>
                            <SerialNo>22</SerialNo>
                            <TypeCode>0</TypeCode>
                        </MassObject>
                        <LaunchLug>
                            <KnownMass>0.5268343291966165</KnownMass>
                            <Density>688.793909</Density>
                            <Material>Cardboard</Material>
                            <Name>Launch lug</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>38.1</Xb>
                            <CalcMass>0.5268343291966165</CalcMass>
                            <CalcCG>12.7</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>25.4</Len>
                            <FinishCode>2</FinishCode>
                            <SerialNo>23</SerialNo>
                            <OD>10.5852</OD>
                            <ID>8.5852</ID>
                        </LaunchLug>
                        <LaunchLug>
                            <KnownMass>0.5268343291966165</KnownMass>
                            <Density>688.793909</Density>
                            <Material>Cardboard</Material>
                            <Name>Launch lug</Name>
                            <KnownCG>0.0</KnownCG>
                            <UseKnownCG>0</UseKnownCG>
                            <Xb>482.6</Xb>
                            <CalcMass>0.5268343291966165</CalcMass>
                            <CalcCG>12.7</CalcCG>
                            <DensityType>0</DensityType>
                            <RadialLoc>0.0</RadialLoc>
                            <RadialAngle>0.0</RadialAngle>
                            <LocationMode>0</LocationMode>
                            <Len>25.4</Len>
                            <FinishCode>2</FinishCode>
                            <SerialNo>24</SerialNo>
                            <OD>10.5852</OD>
                            <ID>8.5852</ID>
                        </LaunchLug>
                    </AttachedParts>
                </BodyTube>
            </Stage3Parts>
            <Stage2Parts/>
            <Stage1Parts/>
        </RocketDesign>
    </DesignInformation>
</RockSimDocument>